#!/bin/bash

if [ -z "$1" ]; then 
	echo "usage: 
	$(basename "$0") template name regno [position] [subname]"
	exit
fi
if [ ! -r "$1" ]; then
	echo "$1 not found"
	exit 1
fi
src="$1"
dest="id/${3}.jpg"
name="$2"
resp="$4"
subname="$5"
photo="photos/$3".jpg
nameshort="$(./initials.py "$name")"

if [ "$name" != "$nameshort" ]; then
  echo "Shortening $name -> $nameshort"
fi

convert \
	"$src" \
	-gravity center \
	-pointsize 75 \
	-fill "#000000" \
	-font "Comfortaa-Bold" \
	-annotate +0+520 "$(./initials.py "$name")" \
	-pointsize 35 \
  -annotate +0+575 "$subname" \
	-font "Open-Sans-Bold" \
	-pointsize 60 \
	-annotate +0+650 "$resp" \
	"$dest" 

magick convert "$dest" "$photo" -gravity Center -geometry 500x500+0+200 -composite "$dest" 
