#!/bin/bash

mkdir -p id
echo "Making all the ID Cards"
template="template.jpg"
while IFS="" read -r line || [ -n "$line" ] ; do
	name="$(echo "$line" | cut -f1)"
  subname="$(echo "$line" | cut -f2)"
	id="$(echo "$line" | cut -f3)"
	resp="$(echo "$line" | cut -f4)"
  echo "$name"
	./badge "$template" "$name" "$id" "$resp" "$subname" &
  while [ "$(jobs | wc -l)" -gt 10 ] ; do sleep 0.1 ; done
done <list
