#!/bin/bash

mkdir -p id
echo "Making all the ID Cards"
let count=1
while IFS="" read -r line || [ -n "$line" ] ; do
	name="$(echo "$line" | cut -f1)"
	dept="$(echo "$line" | cut -f2)"
  regno="$(printf "%03d\n" $count)"
	./badge "$dept.jpg" "$name" "$regno" &
  let count++
  echo "$regno"
  while [ "$(jobs | wc -l)" -gt 20 ] ; do sleep 0.1 ; done
done <list
